name: Generate ASCII Artwork
on: [push]
jobs:
    generate-ascii-artwork:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              
            - name: Install cowsay program
              run: sudo apt install cowsay -y
            
            - name: Execute cowsay command
              run: cowsay -f dragon "Hello, Raja!" >> dragon.txt

            - name: Check file exists
              run: grep -i "raja" dragon.txt

            - name: Read file
              run: cat dragon.txt
            
            - name: List repository files
              run: ls -ltra
